### ISSUE TITLE
Wireleap uses 100% of all cpu cores when connected

### ISSUE THREAD

**Issue by DaVikingMan** [wireleap/client#49]
When connected to wireleap, it uses 100% of the cpu(memory usage is alright)

OS : Arch Linux
Linux kernel version : 5.17.4

Otherwise, this project is amazing, keep up the good work.

**Comment by qrntz** [comment]
thanks for reporting. this sounds like an issue we believed to be fixed recently. are you running the latest version of the client (0.5.5)?

**Comment by alonswartz** [comment]
right, iirc this was fixed in https://github.com/wireleap/common/commit/1b47185affb36b691584f3f9553abebee05397c0 - is the client being built against the latest common?

**Comment by qrntz** [comment]
@alonswartz good point, that commit didn't make it into 0.5.5

**Comment by qrntz** [comment]
fixed in 0.5.6
